version: '3.8'

services:
  wishlist:
    container_name: wishlist-app
    build: ./
    ports:
      - ${WISHLIST_HOSTPORT}:8080
    env_file:
      - .env
    restart: always
  postgres:
    container_name: wishlist-postgres
    image: postgres:16.4
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_HOSTPORT}:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    container_name: wishlist-nginx
    build: ./ui
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: wishlist-certbot
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" 
volumes:
  postgresdata:
