version: '3.8'

services:
  wishlist:
    container_name: wishlist-app-local
    build: ./
    ports:
      - ${WISHLIST_HOSTPORT}:8080
    env_file:
      - .env
    restart: always
  postgres:
    container_name: wishlist-postgres-local
    image: postgres:16.4
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_HOSTPORT}:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    container_name: wishlist-nginx-local
    image: nginx:1.23
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    entrypoint: nginx -g 'daemon off;'
volumes:
  postgresdata:
